version: '3'

networks:
  backend:
    external: true

services:
  csctracker:
    container_name: csc-tracker-finance
    hostname: csc-tracker-finance
    image: krlsedu/csctracker-finance
    restart: always
    networks:
      - backend
    ports:
      - "5050:5000"
