version: '3'

networks:
  backend:
    external: true

services:
  finance:
    container_name: finance
    hostname: finance
    image: krlsedu/csctracker-finance
    restart: always
    networks:
      - backend
